# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nexus.server.proto import media_pb2 as media__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in media_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SttServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTranscribe = channel.stream_stream(
                '/nexus.media.v1.SttService/StreamTranscribe',
                request_serializer=media__pb2.AudioFrame.SerializeToString,
                response_deserializer=media__pb2.TranscriptEvent.FromString,
                _registered_method=True)
        self.Transcribe = channel.unary_unary(
                '/nexus.media.v1.SttService/Transcribe',
                request_serializer=media__pb2.AudioFrame.SerializeToString,
                response_deserializer=media__pb2.TranscriptEvent.FromString,
                _registered_method=True)


class SttServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamTranscribe(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SttServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTranscribe': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTranscribe,
                    request_deserializer=media__pb2.AudioFrame.FromString,
                    response_serializer=media__pb2.TranscriptEvent.SerializeToString,
            ),
            'Transcribe': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=media__pb2.AudioFrame.FromString,
                    response_serializer=media__pb2.TranscriptEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.media.v1.SttService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.media.v1.SttService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SttService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamTranscribe(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nexus.media.v1.SttService/StreamTranscribe',
            media__pb2.AudioFrame.SerializeToString,
            media__pb2.TranscriptEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.media.v1.SttService/Transcribe',
            media__pb2.AudioFrame.SerializeToString,
            media__pb2.TranscriptEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TtsServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSynthesize = channel.stream_stream(
                '/nexus.media.v1.TtsService/StreamSynthesize',
                request_serializer=media__pb2.TtsRequest.SerializeToString,
                response_deserializer=media__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.Synthesize = channel.unary_unary(
                '/nexus.media.v1.TtsService/Synthesize',
                request_serializer=media__pb2.TtsRequest.SerializeToString,
                response_deserializer=media__pb2.AudioChunk.FromString,
                _registered_method=True)


class TtsServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamSynthesize(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synthesize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TtsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSynthesize': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSynthesize,
                    request_deserializer=media__pb2.TtsRequest.FromString,
                    response_serializer=media__pb2.AudioChunk.SerializeToString,
            ),
            'Synthesize': grpc.unary_unary_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=media__pb2.TtsRequest.FromString,
                    response_serializer=media__pb2.AudioChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.media.v1.TtsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.media.v1.TtsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TtsService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamSynthesize(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nexus.media.v1.TtsService/StreamSynthesize',
            media__pb2.TtsRequest.SerializeToString,
            media__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.media.v1.TtsService/Synthesize',
            media__pb2.TtsRequest.SerializeToString,
            media__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VadServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamVad = channel.stream_stream(
                '/nexus.media.v1.VadService/StreamVad',
                request_serializer=media__pb2.AudioFrame.SerializeToString,
                response_deserializer=media__pb2.VadEvent.FromString,
                _registered_method=True)


class VadServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StreamVad(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamVad': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamVad,
                    request_deserializer=media__pb2.AudioFrame.FromString,
                    response_serializer=media__pb2.VadEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.media.v1.VadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.media.v1.VadService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VadService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamVad(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/nexus.media.v1.VadService/StreamVad',
            media__pb2.AudioFrame.SerializeToString,
            media__pb2.VadEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LidServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectLanguage = channel.unary_unary(
                '/nexus.media.v1.LidService/DetectLanguage',
                request_serializer=media__pb2.LidRequest.SerializeToString,
                response_deserializer=media__pb2.LidResponse.FromString,
                _registered_method=True)


class LidServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def DetectLanguage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LidServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectLanguage,
                    request_deserializer=media__pb2.LidRequest.FromString,
                    response_serializer=media__pb2.LidResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.media.v1.LidService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.media.v1.LidService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LidService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.media.v1.LidService/DetectLanguage',
            media__pb2.LidRequest.SerializeToString,
            media__pb2.LidResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/nexus.media.v1.HealthService/Check',
                request_serializer=media__pb2.HealthRequest.SerializeToString,
                response_deserializer=media__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Meta = channel.unary_unary(
                '/nexus.media.v1.HealthService/Meta',
                request_serializer=media__pb2.MetaRequest.SerializeToString,
                response_deserializer=media__pb2.MetaResponse.FromString,
                _registered_method=True)


class HealthServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Meta(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=media__pb2.HealthRequest.FromString,
                    response_serializer=media__pb2.HealthResponse.SerializeToString,
            ),
            'Meta': grpc.unary_unary_rpc_method_handler(
                    servicer.Meta,
                    request_deserializer=media__pb2.MetaRequest.FromString,
                    response_serializer=media__pb2.MetaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nexus.media.v1.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nexus.media.v1.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.media.v1.HealthService/Check',
            media__pb2.HealthRequest.SerializeToString,
            media__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Meta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nexus.media.v1.HealthService/Meta',
            media__pb2.MetaRequest.SerializeToString,
            media__pb2.MetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
